[workspace]
description = "Various experiments with interactive multimedia algorithms"
members = [
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"
authors = ["Cooper Johnson <lavosprime@gmail.com>"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
